name: download_letcode

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate epub and html
        run: |
          python main.py
      - name: Commit and push
        run: |-
          git config --global user.email "githubaction@example.com"
          git config --global user.name "github-action"
          git diff --quiet || (git add chapters.pickle out.html track.conf "Leetcode Questions.epub" && git commit -m "Update with new problems")
          git push origin HEAD:main