name: download_letcode_manual

on:
  workflow_dispatch:
    inputs:
      MAXIMUM_NUMBER_OF_PROBLEMS:
        description: 'Number of problems to download'     
        default: '30'
      SLEEP_TIME_PER_PROBLEM_IN_SECOND:
        description: 'Number of seconds to wait after downloading each problem'
        default: '8'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate epub and html
        run: |
          python main.py
        env:
          MAXIMUM_NUMBER_OF_PROBLEMS: ${{ github.event.inputs.MAXIMUM_NUMBER_OF_PROBLEMS }}
          SLEEP_TIME_PER_PROBLEM_IN_SECOND: ${{ github.event.inputs.SLEEP_TIME_PER_PROBLEM_IN_SECOND }}
      - name: Commit and push
        run: |-
          git config --global user.email "githubaction@example.com"
          git config --global user.name "github-action"
          git diff --quiet || (git add chapters.pickle out.html track.conf "Leetcode Questions.epub" && git commit -m "Update with new problems")
          git push --force-with-lease